### ISSUE TITLE
how build many queue in a application

### ISSUE THREAD

**Issue by fangjj** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#14]
how build many queue in a application

**Comment by fangjj** [comment]
Any update? I real need many queue in my application, so now can you have any advice for me? thank you!

**Comment by msavin** [comment]
Please familiarize yourself with the code and be more descriptive when creating GitHub issues.

**Comment by fangjj** [comment]
sorry, i'm poor in english. thank you fro your time. I need two or more queen in one application, for example, sms_queue, mail_queue and so on. The sms_queue just send sms, and the mail queue just send email, and this queues  are separate in mongo collection named sms_jobs_data collection, mail_jobs_data collection. But msavin:sjobs use one queue named jobs_data collection to send email and sms. I just want everyone queue has own collection and do one thing. can you understand what i explain. thank you.

**Comment by fangjj** [comment]
just the same issue about it 
Duplicate of #5

**Comment by msavin** [comment]
The package will automatically create two queues and store them into `jobs_data`. That collection is indexed by the queue name, so it would be like having many queues but in one collection.
