### ISSUE TITLE
how to limit the max the pending state job in one queue？

### ISSUE THREAD

**Issue by fangjj** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#15]
how to limit the max the pending state job in one queue and throw a error when put more job as queue is the fulled？

**Comment by msavin** [comment]
There is no support for this right now. However, you could implement it yourself. For example:

```javascript
Jobs.register({
	"sendEmail": function () {
		if (JobsInternal.Utilities.Collection.find().count() <= 1000) {
			// ...
		}
	}
})
```
