### ISSUE TITLE
defer vs on

### ISSUE THREAD

**Issue by dillongreen** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#19]
wouldn't it be better to rename `on` to `defer`? I had to read twice to grasp the semantics when it's actually trivial, it's deferring a job to a future date. If not calling it `defer` then maybe `run on`, still easier/faster to grasp than just `on`.

The task manager Omnifocus is a good example, different thing but same semantics in principle, they also call it `defer` when a task is shifted to start at some future date...

**Comment by msavin** [comment]
The play here is on the `in` and `on`, which can be used to modify the date from which the job will run in a descriptive way. With the new 2.0, there is now support for `date`, which lets you pass in whatever date you would want the job to run on. I hope that clarifies it.
