### ISSUE TITLE
Cannot import the module using ES6 ?

### ISSUE THREAD

**Issue by zeiitoun** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#20]
import { Jobs } from 'meteor/msavin:jobs' is failing on startup ... 

W20180115-17:02:37.789(1)? (STDERR) Error: Cannot find module 'meteor/msavin:jobs'

Any idea why ? (I added it using atmosphere) 

------
EDIT : typo on readme, import { Jobs } from 'meteor/msavin:**s**jobs';

s missing.

**Comment by msavin** [comment]
indeed - forgot to fix that - thanks for reminder :) is it working now for you?

**Comment by zeiitoun** [comment]
Yep perfectly working !
