### ISSUE TITLE
Debugging story/development mode? 

### ISSUE THREAD

**Issue by stevenqzhang** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#21]
Request: could there be some sort of scenario covered where we could run the jobs in dev mode, either by accelerating the clock manually, or having all the jobs run at a "debug" interval in addition to actual interval used in prod?

**Comment by msavin** [comment]
Can you clarify what you mean? Currently, the package will run the same way in development as it would in production.

**Comment by msavin** [comment]
Oh, I think you mean like a dev tool? Maybe in the future 😁

**Comment by stevenqzhang** [comment]
Yep! I meant a dev tool, or some sort of process where the developer could fast forward in clock and see the jobs being triggered  :)

The issue I'm facing is that I have jobs that are running 2-4 weeks in the future, and those jobs create future jobs depending on the status of a user's Google calendar, so it's really hard to test it in a short period of time

**Comment by msavin** [comment]
Check out the readme :)
