### ISSUE TITLE
Jobs.reschedule does not accept Date objects

### ISSUE THREAD

**Issue by gregcarlin** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#22]
I'm trying to reschedule an existing job for a given date, so I'm using the following code:

    Jobs.reschedule(<jobId>, {
        date: new Date(<date specification>),
    });

However, when this is run I get the following error:

    Error: Match error: Expected plain object in field date
        at exports.check (packages/check.js:55:15)
        at Object.Jobs.reschedule (packages/msavin:sjobs/server/api.js:129:2)
        ...

Should I be specifying the `date` as something other than a `Date` object? When I create the job in a similar way everything seems to work as it should:

    Jobs.run('<name>', <arg>, {
        date: new Date(<date specification>),
    });

**Comment by msavin** [comment]
Hey Greg, I was checking the Date field to be an object - it turns out Meteor rejects that and supports checking for Dates. The new version should have it working correctly.

**Comment by gregcarlin** [comment]
Thanks so much!
