### ISSUE TITLE
reschedule does not work if there is only a single job of that name

### ISSUE THREAD

**Issue by gary-menzel** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#29]
I'm new to the package and was just doing some testing (only a a few hours on it - looking to replace the vsivsi job collection package).

I used the example `sendReminder` and added in a `reschedule` instead of `success` and set it for 10 seconds.

If I run it with a clean `jobs_data` collection then it never triggers again.

However, if I shut the server down and run it up again (and now there are two `sendReminder` records) then they both run at the expected interval.

NOTE: if I then delete one of the two records out while the job is still running, it then stops and does not trigger the job any more.

I had a look at the code quickly and there seems to be a blocker in there if the same `_id` was just run in a Queue.

https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/blob/84df2fa3cebb9b50b6b3b7ce3ffc3400c5c10b12/package/server/imports/operator/queue/index.js#L86

This would make sense if there were two records for that queue.  One would execute and then the other - alternating between the two.  Maybe this query also needs to look at the status to see if it is `pending` ?

**Comment by msavin** [comment]
Good catch! I just implemented this feature in case a MongoDB read happens before a write has resolved - but it looks like there are some drawbacks. I will try to get a solution in place in the next week. If you need to use this functionality immediately, I can suggest downgrading one version.

**Comment by gary-menzel** [comment]
Thanks for the response (and I understand what you mean).  For my particular use case I could probably just run two of them to trick it into working as I want - schedule them to run around each other.  The repeating job is mainly to do a regular pull from an imap account.  I could even just create another job to run when that one is finished.  As long as it keeps running there is not a big concern over accurate frequency.

But, it would be nice to have reschedule working with a single queue/job record.

Thanks.

**Comment by msavin** [comment]
Fixed in the latest 3.0
