### ISSUE TITLE
Quite Confusing Delay Schedule

### ISSUE THREAD

**Issue by skemb321** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#3]
Hi Max, good job!

But can you please elaborate on this?:
```
The date object will be updated in the order that is specified.
 For example, if you set the job to run in 1 year, an on year 2037, the year will be 2037. 
However, if you set the job to run on year 2037, and in 1 year, the year will be 2038.
```

Do u mean that these jobs are not the same?
1
```
Jobs.add("sendReminderEmail", "john@smith.com", "The future is here!", {
    in: {
        days: 1,
        hours: 13
    }, 
    on: {
        minute: 13,
        year: 2037
    }
});
```

2
```
Jobs.add("sendReminderEmail", "john@smith.com", "The future is here!", {
    on: {
        days: 1,
        hours: 13
    }, 
    in: {
        minute: 13,
        year: 2037
    }
});
```

Didn't try this though but it confused me while reading the instructions.

Thanks in advance.

**Comment by msavin** [comment]
Hey man - thanks for the interest.

In the example that you used, it would be the same because there are no conflicting options. 

However, in this case, there year would become 2037.
```
Jobs.add("sendReminderEmail", "john@smith.com", "The future is here!", {
    on: {
        days: 1,
        hours: 13,
        year: 2036
    }, 
    in: {
        minute: 13,
        year: 1 
    }
});
```
But in this one, it would be 2036:
```
Jobs.add("sendReminderEmail", "john@smith.com", "The future is here!", {
    in: {
        minute: 13,
        year: 1 
    },
    on: {
        days: 1,
        hours: 13,
        year: 2036
    }, 
});
```
However, it maybe best to omit that part from the instructions. The thing is, I'm planning to enable functions as an input, so that's where it might get tricky: 
```javascript
Jobs.add("sendReminderEmail", "john@smith.com", "The future is here!", {
    in: {
        minute: 13,
        year: 1 
    },
    on: {
        days: 1,
        hours: 13,
        year: function () {
                if (x) { 
                        return 2037
                }
    }, 
});
```

**Comment by skemb321** [comment]
Thanks! It's clear now. :+1:

**Comment by luixal** [comment]
Hey, I think the package is no longer supported, but I haven't find anything better for this than using [LaterJS](https://bunkat.github.io/later/).

Supporting that may be a different package? `SteveJobs-meteor-jobs-queue-laterjs`?

**Comment by msavin** [comment]
@luixal not sure which package we are discussing - but maybe this is relevant: `Jobs.run` now supports a `date` field so you can plug in any library in there. 

Going to close this ticket out as it seems old/resolved - but feel free to open a new one.
