### ISSUE TITLE
[FEATURE REQUEST] add 'serverId' to Jobs.configure({options}) - use instead of Random.id() if not null

### ISSUE THREAD

**Issue by gary-menzel** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#30]
The use case for this is in a situation like Meteor Galaxy where each instance is already allocated an ID and it would be useful to be able to correlate the Galaxy instance ID with the instance that is running the queues.

With that information it would be very easy to restart the instance and, hence, force another instance to take over.

[Also - it seems that the Dominator adds a record to jobs_dominator for each registered job but it only sets the `lastPing` on one of them. I would probably only expect one record for the current server running the queues.  Or a separate one for each job name (each updating separately)]

**Comment by msavin** [comment]
Good idea - and easy to implement. 

Regarding Dominator - it does so for you to see which servers have been running the jobs during what time periods. It should be keeping each servers state with-in one document though. The only time a new document gets created is when a new server id is created.

Do you know how to get the Galaxy server id?

**Comment by gary-menzel** [comment]
Yes - getting the Galaxy ID is fairly easy..... `process.env.GALAXY_CONTAINER_ID`. It is made up of the App ID and the instance ID and looks something like `Ss8o4Y6KrvFBKKkqM-3n28`.

My observation on my local machine (only running one instance) was that multiple records were getting created for the same `serverId`.  Here's a screenshot from the database table:

![image](https://user-images.githubusercontent.com/5697099/36371388-0b35245e-15b6-11e8-872a-1baa0bf87d20.png)

**Comment by msavin** [comment]
Good catch - MongoDB is failing pretty hard here.

If you have more than one queue, they all start at the same time and `dominator` runs the database check for each one. Then, it runs the `upsert` for each one. It looks like if you have multiple upserts being called simultaneously, MongoDB may not notice and just insert all of them. 

I'm debating some kind of re-write, or to set a unique index on the `serverId` field of the document.

**Comment by gary-menzel** [comment]
What about a `timestamp` (or the `created`) that could be combined with the `serverId` when checking ?

I realise `upsert` should handle it but maybe this is a case for a `read` then `update`.  Given the timeout on the checks the "inactive" ones do, I don't think that would be an issue.

Looks like MongoDB 4 will have transactions across documents - but that still may be a ways off.

**Comment by msavin** [comment]
There is a read that preceeds the `upsert`, but for some reason it's not being recognized. I suspect its because `dominator` runs a few times for each queue, immediately on startup. The upserts are happening milliseconds apart, it might be a bit too fast for MongoDB.

Transactions - I'm very excited about it - indeed, MongoDB 5.0 might be a glorious release.

**Comment by msavin** [comment]
@gary-menzel good news, this and more is coming to v3. I have the test version on a new branch, feel free to try it and let me know what you think

Branch
https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/tree/v3

Changes
https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/blob/v3/CHANGES.md

**Comment by gary-menzel** [comment]
Looks like a lot coming (had a quick look at the changes).  I'll have to digest this.

At the moment, I am basically just creating a new job to get the "repeat" functionality but it looks like you have thought this through.  I'll probably get my head into it this coming weekend (other things with emails and templates to be working on in the meantime).

Thanks for getting to this.

**Comment by msavin** [comment]
@gary-menzel thanks for the suggestion - I just pushed up 3.0 with this featuer - it would be great to hear of your experience with it.
