### ISSUE TITLE
feature question

### ISSUE THREAD

**Issue by haojia321** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#32]
Hi,
I found this package is very interesting but I'm not sure if this package will fulfill my requirement.
We have a dedicated server to do video compressing work. Our requirement is:
* Server can run up to X threads at same time. Each thread will be compressing one video file using ffmpeg. The actual video compressing code in ffmpeg is async.
* Thread is considered as done and deleted when it finishes the video processing.
* Server checks how many threads are running in every Y seconds interval. If total running threads are less than X, server can create new thread to process video file.

The tricky part here is new job cannot run until current total running job count is less than X. I didnt find how to achieve this in this package.

**Comment by msavin** [comment]
A limitation, or feature, of the package is that it runs jobs consecutively, one after another, so I'm not sure if it would fit your needs here. I might change this, or provide an alternative mechanism, but right now I have not found the need for it.

**Comment by haojia321** [comment]
Hi @msavin ,
If one job has a async callback. is there anyway that we mark this job is done when the async callback is executed?
