### ISSUE TITLE
How to schedule jobs to repeat at a particular time?

### ISSUE THREAD

**Issue by bhanuprasad04** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#33]
I want to run the job at particular time like everyday at 12AM, how can i achieve this, below are my sample code

[Jobs.register({
everydayjob: function () {
console.log("calling everydayjob");
this.success("sucess");
return;
}
});
// schedule the job
Jobs.run("everydayjob",{
in: {
hours: 24
}
});

How can i configure at run the job at particular time . Thanks in advance

**Comment by msavin** [comment]
This functionality is not supported yet. It's coming soon though.

**Comment by msavin** [comment]
Good news: I have the v3 on a test branch. You can try the functionality out. It would be great to hear your feedback if you do.

Branch
https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/tree/v3

Changes
https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/blob/v3/CHANGES.md

Both are draft mode - but the package looks to be working. I'm going to take a week break from it before doing another set of tests and publishing it.
