### ISSUE TITLE
Updating jobs

### ISSUE THREAD

**Issue by jmoseley** [msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue#34]
During local development I'm noticing that it creates a new copy of a job whenever the server restarts. I expected subsequent restarts to simply update the existing job (that has the same job id). Is there some mechanism here that I am not understanding?

I expect that the implementations of my job will change over time, how do I ensure that new jobs that I register with new code overwrite existing versions instead of creating a new, different job?

It appears the calling `Job.run` at server startup creates a new entry in the `jobs_data` table, and then eventually all of these copies of the job run on the defined run schedule.

**Comment by jmoseley** [comment]
Oh I think another confounding factor is that this is a repeating job, so I do not end with `this.success()`, I end with `this.reschedule(...)`.

```
export function registerJob({
  name,
  run,
}: {
  name: string;
  run: (args: RunArguments) => Promise<void>;
}) {
  console.info(`Registering ${name} job.`);

  Jobs.register({
    [name](args: RunArguments) {
      /* Forward context/params to 'run' method - execute in a fiber-aware await to
       allow regular async syntax in provided function */
      MeteorPromise.await(run.apply(this, args));
    },
  });
}

const RUN_CONFIG: RunConfig = {
  in: {
    minutes: 5,
  },
};

export const JOB_ID = 'job1';

async function runFunction(_args?: RunArguments) {
  const self: JobInstance = this;

  // ... do a bunch of stuff

  // Run the job again, so it keeps looping.
  self.reschedule(SYNC_USER_ACTIVITIES_RUN_CONFIG);
}

registerJob({ name: JOB_ID, run: runFunction });
console.info(`Running ${JOB_ID} job.`);
Jobs.run(JOB_ID, null, RUN_CONFIG);
```

And the result is many entries in the `job_data` collection, all with the `pending` state.

**Comment by gary-menzel** [comment]
#29  may also be related - I believe there is a V3 being planned that will readdress how rescheduling works.

**Comment by msavin** [comment]
This is working as it should. The problem is, the server is executing `Jobs.run(JOB_ID, null, RUN_CONFIG)` every time it starts up. You only need to run it once to "kickstart" it.

**Comment by jmoseley** [comment]
Oh that's interesting. Is there a way to check if that "jumpstart" has already been done? Allows me to ensure that the job is started as the code slides through different environments (and eventually to production).

**Comment by msavin** [comment]
You could do something like: 

```javascript
if (!JobsInternal.Utilities.collection.findOne({name: name})) {
     Jobs.run(JOB_ID, null, RUN_CONFIG);
} 
```

FYI - as @gary-menzel mentioned - there is a v3 on the way which will feature `this.replicate` so that each instance of the job has its own document. More info in CHANGES.md

https://github.com/msavin/SteveJobs...meteor.schedule.background.tasks.jobs.queue/tree/v3

**Comment by jmoseley** [comment]
That seems reasonable. Is V3 close to stable?

**Comment by jmoseley** [comment]
And what's the easiest way to install V3?

**Comment by msavin** [comment]
I just pushed it - so run `meteor update` and you'll have it. Let me know how it goes. :)

**Comment by mazak** [comment]
Perfect!

**Comment by jmoseley** [comment]
If you are curious, [this](https://github.com/jmoseley/strava-challenge/blob/e6dfdfa6352b8ca69dc90425eb5ce22dc0947eb0/server/jobs/index.ts) is what I came up with to wrap it into a cron job.

My business logic lives in an `async` function the returns `SUCCESS` or `RETRY` and the wrappers in ^ do the work of rescheduling or replicating depending on the result. Also cancels the pending version on creation so the job can be updated with new code changes safely.

**Comment by msavin** [comment]
@jmoseley thanks for sharing and glad you got it working. Unfortunately, I'm not up on the latest es6 practicers, but once I am I will be sure to take a look :)

**Comment by jmoseley** [comment]
Ah ya it's typescript, so might be hard to grok up front, but hopefully it helps someone else get started.

**Comment by gary-menzel** [comment]
@jmoseley Although I don't use TS, I found it useful. I have been using Promise a fair bit but somehow missed that there is a Meteor version available as a package.  It looks like it makes working with`Meteor.bindEnvironment` much more seamless. Thanks for the link.
